### ISSUE TITLE
Add admin entities/functionality

### ISSUE THREAD

**Issue by GroovinChip** [lukepighetti/mastodon_dart#19]
Relates to #14 

DISCUSSION: Currently we have zero support for admin related things. @lukepighetti do you think we should add admin support to existing entities or make them separate? 

todo:
- [ ] Add admin endpoints, regular and mock https://docs.joinmastodon.org/methods/admin/
- [ ] Resolve discussion about whether to add admin support to existing entities or to make separate admin entities

**Comment by lukepighetti** [comment]
I don't have the bandwidth for this task but it would be a nice feature to have for sure

**Comment by GroovinChip** [comment]
The real question is how to even do it

**Comment by lukepighetti** [comment]
this is only for people who run instances, yeah?

**Comment by GroovinChip** [comment]
Yes
