### ISSUE TITLE
Implement Timelines.listTimeline()

### ISSUE THREAD

**Issue by lukepighetti** [lukepighetti/mastodon_dart#2]
https://docs.joinmastodon.org/methods/timelines/lists/

https://github.com/lukepighetti/mastodon-dart/blob/76cc1dd6917d0bcc14757cdf99f83d7d781c9d76/lib/src/endpoints/timelines.dart#L130-L146

**Comment by GroovinChip** [comment]
This seems to be implemented already? Can you clarify this please @lukepighetti?

**Comment by lukepighetti** [comment]
It appears to be an issue that was handled but not closed
