### ISSUE TITLE
Pub docs only pick up on the mock library

### ISSUE THREAD

**Issue by GroovinChip** [lukepighetti/mastodon_dart#25]
https://pub.dev/documentation/mastodon_dart/latest/

@lukepighetti any idea why this might be?

**Comment by lukepighetti** [comment]
it's because the actual library is a sub-library, https://pub.dev/documentation/mastodon_dart/latest/mastodon_dart/mastodon_dart-library.html, course of action would be to restructure the project to have the mocks extend the implementation instead of the opposite (which is how it is now)
