### ISSUE TITLE
Implement file, focus

### ISSUE THREAD

**Issue by lukepighetti** [lukepighetti/mastodon_dart#6]
https://github.com/lukepighetti/mastodon-dart/blob/3f4b0103ab35e048960161f10099ccfe21f8011f/lib/src/endpoints/media_attachments.dart#L16

https://github.com/lukepighetti/mastodon-dart/blob/3f4b0103ab35e048960161f10099ccfe21f8011f/lib/src/endpoints/media_attachments.dart#L40

**Comment by GroovinChip** [comment]
Completed long ago, closing
